### ISSUE TITLE
Module 2 - Exercise 1 - Task 1 - Step 6

### ISSUE THREAD

**Issue by shirivo** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#119]
Specify what should be the password for database login because the students get confused. More guidelines about where the password is or simply: "use the same password that you use to login the VM".

Also, remove the part that says "use the password supplied when deployed the lab" because students understand that need to deploy something. That step is unnecessary for LODS environment.

![image](https://user-images.githubusercontent.com/620849/121940061-f04edf80-cd0a-11eb-8405-0eb24e7f8a10.png)

**Comment by ZekeStarr** [comment]
Hi Shirivo,

This is an item that we, at LODS, will need to account for in the instructions. Instead of modifying the steps here in GitHub, we can use a string replacement to replace that with the password we're deploying with.

We'll get this into Production on our labs soon and let you know when it's done.

**Comment by ZekeStarr** [comment]
Hi Shirivo,

We have updated our (LODS') lab instructions to display the password used during deployment instead. Thank you for posting the issue!

@ctesta-oneillmsft This is an LODS-side issue, and we have updated our instructions to account. Thank you!
