### ISSUE TITLE
Replace the installation of Azure Data Studio with instructions on how to create tables in the Query editor.

### ISSUE THREAD

**Issue by tibor19** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#61]
Installing Azure Data Studio serves no learning purpose and is only diluting the experience. The same outcome (creating a bunch of tables) can be achieved by running the queries in the Query Editor. In that way we can skip the need of having an extra VM only for this purpose.

**Comment by joelhulen** [comment]
Our intention is that the lab hosting providers will make Azure Data Studio available to students in a VM so they don't have to install it. If you are referring to Module 2, then creating tables is part of the learning process since this is about how to create star and snowflake schemas. Students need to be familiar with the fields, how tables relate, the syntax, etc.

We can consider having users use the Query Editor in the portal instead in a future update.

**Comment by tibor19** [comment]
I do want the students to create the tables, however they are asked to install Azure Data Studio as part of the pre-requisites for the lab, and then asked to use it during the lab. There is nothing in ADS that adds value compared to query editor, it just feels that we are throwing there, just because we want to show it exists.

**Comment by ctesta-oneillmsft** [comment]
Comments are noted for future updates
