### ISSUE TITLE
LODS: Module 05, Exercise 3, Task 1, Step 1

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure#95]
![image1](https://user-images.githubusercontent.com/33545180/119793964-f8b3b780-bece-11eb-86b1-8aa2eb9a767e.jpg)
the /online-user-profiles directory doesn't exist in the ADLS so this fails, cannot finish this exercise

**Comment by Kaijisse** [comment]
I don't know for sure if the file is not in the datalake, but in the new instructions exercise 2, task 1, nr 5, you would have already ran the cell to set datalake as your datalake name. In exercise 3, task 1, step 1, in the code cell, in the lab, it's not mentioned to pass through the datalake variable again What I see in the screenshot is that it doesn't exist but not sure because they ran datalake variable again in the screenshot they sent. The new instructions for this command don't include datalake = 'xxxx'
See below:
df = (spark.read \
.option('inferSchema', 'true') \
.json('abfss://wwi-02@' + datalake + '.dfs.core.windows.net/online-user-profiles-02/*.json', multiLine=True)
)



df.printSchema()#

Still investigating.

**Comment by joelhulen** [comment]
There must have been a failure in your environment setup. You should see JSON files in the `wwi-02\online-user-profiles-02` path in ADLS Gen2.

![image](https://user-images.githubusercontent.com/5950304/119817804-673b4a00-bebc-11eb-8515-7a08cd47814d.png)

**Comment by ctesta-oneillmsft** [comment]
Following on from this investigation.

I have added an instruction in Exercise 2, Task 1, step 4 as follows:

".... **Do not run/execute the cell at this stage**, as we need to create a variable for the name of your datalake first.".

This should mitigate the student from automatically running a cell, even when there id no instruction to do so. I think what has happened, is that the cell has been run, the tester has read that they have to add more code to the cell, but by the time they have done this the cell has been populated with the additional code, but has not actually been executed. Therefore as you run the code for Module 05, Exercise 3, Task 1, Step 1, it relies on the data lake variable that has not been instantiated in the Spark instance.

Adding this instruction will mitigate that
